// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Data.Configurations
{
    public partial class HashTagConfiguration : IEntityTypeConfiguration<HashTag>
    {
        public void Configure(EntityTypeBuilder<HashTag> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__HashTags__3214EC0780719B2F");

            entity.HasIndex(e => new { e.TweetId, e.HashTag1, e.CreatedAt }, "UC_HashTags").IsUnique();

            entity.Property(e => e.HashTag1)
            .IsRequired()
            .HasMaxLength(350)
            .HasColumnName("HashTag");
            entity.Property(e => e.TweetId)
            .IsRequired()
            .HasMaxLength(50);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<HashTag> entity);
    }
}
