// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Data
{
    public partial class SpGetTop10HashTagsByHourWindowResult
    {
        public string HashTag { get; set; }
        public int? HashTagCount { get; set; }
    }
}
