// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Data.Configurations;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
#nullable disable

namespace Data;

public partial class TwitterStreamDbContext : DbContext
{
    public TwitterStreamDbContext(DbContextOptions<TwitterStreamDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<HashTag> HashTags { get; set; }

    public virtual DbSet<Tweet> Tweets { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
            modelBuilder.ApplyConfiguration(new Configurations.HashTagConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.TweetConfiguration());

        OnModelCreatingGeneratedProcedures(modelBuilder);
        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
